src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]

class User implements UserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;
  /** *  @Assert\NotBlank(message=" FullName doit etre non vide")
     * @Assert\Length(
     *      min = 5,
     *      minMessage=" Entrer un nom au mini de 3 caracteres"
     *
     *     )
     * @ORM\Column(type="string", length=255)
     */
    #[ORM\Column(length: 255)]
    private ?string $full_name = null;
    /** *  @Assert\NotBlank(message=" Email doit etre non vide")
     * @Assert\Length(
     *      min = 5,
     *      minMessage=" Entrer une adresse email"
     *
     *     )
     * @ORM\Column(type="string", length=255)
     */

    #[ORM\Column(length: 255)]
    private ?string $email = null;
/** *  @Assert\NotBlank(message=" Password doit etre non vide")
     * @Assert\Length(
     *      min = 5,
     *      minMessage=" Entrer un nom au mini de 3 caracteres"
     *
     *     )
     * @ORM\Column(type="string", length=255)
     */
    #[ORM\Column(length: 255)]
    private ?string $password = null;
/** *  @Assert\NotBlank(message=" UserType doit etre non vide")
     * @Assert\Length(
     *      min = 5,
     *      minMessage=" Entrer un nom au mini de 3 caracteres"
     *
     *     )
     * @ORM\Column(type="string", length=255)
     */
    #[ORM\Column(length: 255)]
    private ?string $user_type = null;
    #[ORM\Column]
    private ?array $roles = [];


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullName(): ?string
    {
        return $this->full_name;
    }

    public function setFullName(string $full_name): static
    {
        $this->full_name = $full_name;

        return $this;
    }
    

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getUserType(): ?string
    {
        return $this->user_type;
    }

    public function setUserType(string $user_type): static
    {
        $this->user_type = $user_type;

        return $this;
    }
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function getSalt(): ?string
    {
        return null;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function getUsername(): string
    {
        return (string) $this->email;
    }

    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType; // Importez SubmitType

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Ajouter', SubmitType::class, [
                'label' => 'Ajouter', // Définissez le libellé du bouton
                'attr' => ['class' => 'btn btn-primary']
            ])
            ->add('email')
            ->add('full_name')
            ->add('user_type')
            ->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'first_options' => ['label' => 'Password'],
                'second_options' => ['label' => 'Confirm Password']
            ]);
    }
    

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;  // Ajout de l'import UserRepository
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UserController extends AbstractController
{
    private $passwordEncoder;

    public function __construct(UserPasswordEncoderInterface $passwordEncoder)
    {
        $this->passwordEncoder = $passwordEncoder;
    }
    #[Route('/app_user', name: "app_user")] // Modifier le nom de la route
    public function app_user(): Response // Renommer la méthode
    {   
        $user = $this->getDoctrine()->getManager()->getRepository(User::class)->findAll();
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
            'users' => $user
        ]);
    }
   

    #[Route('/app_user', name: "app_user")] // Modifier le nom de la route
    public function index(): Response // Renommer la méthode
    {   
        $user = $this->getDoctrine()->getManager()->getRepository(User::class)->findAll();
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
            'users' => $user
        ]);
    }
    
    
    #[Route('/admin', name: "display_admin")]
    public function indexAdmin(): Response
    {   
        return $this->render('Admin/index.html.twig');
    }
    #[Route('/client', name: "display_client")]
    public function indexClient(): Response
    {   
        return $this->render('Client/index.html.twig');
    }

    #[Route('/adduser', name: "adduser")]
    public function adduser(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = new User();
        $user->setRoles(['ROLE_USER']);
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        
        
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($user);
            $user->setPassword($this->passwordEncoder->encodePassword($user, $user->getPassword()));
            $entityManager->flush();
            return $this->redirectToRoute('app_login');
        }
        
        
        return $this->render('user/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/deleteUser/{id}', name: "supp_user")]
    public function suppressionUser($id, UserRepository $repo): Response
    {   
        $em = $this->getDoctrine()->getManager();
        $user = $repo->find($id);
        $em->remove($user);
        $em->flush();
        return $this->redirectToRoute('app_user');
    }

    #[Route('/modifuser/{id}', name: "modifuser")]
    public function modifuser(Request $request, $id): Response
    {
        $user = $this->getDoctrine()->getManager()->getRepository(User::class)->find($id);
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            
            return $this->redirectToRoute('app_user');
        }
        
        
        return $this->render('user/update.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    
    
}

templates/user/add.html.twig
{% extends 'base.html.twig' %}

{% block header %}
{% endblock %}

{% block footer %}
{% endblock %}

{% block sidebar %}
{% endblock %}

{% block body %}
<div class="container">

    <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

                    <div class="d-flex justify-content-center py-4">
                        <a href="index.html" class="logo d-flex align-items-center w-auto">
                            <img src="assets/img/logo.png" alt="">
                            <span class="d-none d-lg-block">Creation d'un compte </span>
                        </a>
                    </div><!-- End Logo -->

                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="pt-4 pb-2">
                                <h5 class="card-title text-center pb-0 fs-4">Create an Account</h5>
                                <p class="text-center small">Enter your personal details to create account</p>
                                <p class="text-center small">Entrer les données personelles pour la creation d'un compte FlixWork</p>

</div>
                    {{ form_start(form,{attr:{novalidate:'novalidate'}}) }}
                                                        <div class="row g-3 needs-validation" novalidate="">

                                <div class="col-12">
                                    <label for="yourName" class="form-label">Your Name</label>
                                    {{ form_widget(form.full_name, {attr: {'class': 'form-control'}}) }}

                                </div>
                                {{ form_errors(form.full_name, {attr: {'class': 'text-danger'}}) }}

                                <div class="col-12">
                                    <label for="yourEmail" class="form-label">Your Email</label>
                                    {{ form_widget(form.email, {attr: {'class': 'form-control'}}) }}
                                   
                                </div>
                                {{ form_errors(form.email, {attr: {'class': 'text-danger'}}) }}

                                                                <div class="col-12">
                                    <label for="yourEmail" class="form-label">UserType</label>
                                    {{ form_widget(form.user_type, {attr: {'class': 'form-control'}}) }}
                                    
                                </div>
                                    {{ form_errors(form.user_type, {attr: {'class': 'text-danger'}}) }}

                                <div class="col-12">
                                    <label for="yourPassword" class="form-label">Password</label>
                                    {{ form_widget(form.password.first,{'attr':{'class':'form-control'}}) }}
                                    
                                </div>
                                                                    {{ form_errors(form.password.first, {attr: {'class': 'text-danger'}}) }}

                                <div class="col-12">
                                    <label for="yourPassword" class="form-label">Confirm Password</label>
                                    {{ form_widget(form.password.second,{'attr':{'class':'form-control'}}) }}
                                   
                                </div>
                                                                    {{ form_errors(form.password.second, {attr: {'class': 'text-danger'}}) }}

                                <div class="col-12">
                                    <div class="form-check">
                                        <input class="form-check-input" name="terms" type="checkbox" value="" id="acceptTerms" required="">
                                        <label class="form-check-label" for="acceptTerms">I agree and accept the <a href="#">terms and conditions</a></label>
                                     
                                    </div>
                                </div>
                                <div class="col-12">
                                    <button class="btn btn-primary w-100" type="submit">Create Account</button>
                                </div>
                                <div class="col-12">
                                    <p class="small mb-0">Already have an account? <a href="login">Log in</a></p>
                                </div>
                            </div>
                            <div class="col-sm-10" style="display: flex;align-items: center;justify-content: center">

                        {{ form_widget(form.Ajouter,{'attr':{'class':'btn btn-primary'}}) }}
                    </div>
                            {{ form_end(form) }}
                        </div>
                    </div>

                    <div class="credits">
                        <!-- All the links in the footer should remain intact. -->
                        <!-- You can delete the links only if you purchased the pro version. -->
                        <!-- Licensing information: https://bootstrapmade.com/license/ -->
                        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
                        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                    </div>

                </div>
            </div>
        </div>
    </section>

</div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}


{% block sidebar %}
{% endblock %}

{% block body %}
<div class="row" style="display: flex;align-items: center;justify-content: center;margin-top: 150px;">
<div class="col-lg-6">

<div class="card">
            <div class="card-body">
            <a href="{{path('adduser')}}"><i class="ri-arrow-left-circle-fill" style="font-size: 50px;"></i>
            
              <h5 class="card-title">Liste Des Utilisateurs</h5>

              <!-- Table with stripped rows -->
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>FullName</th>
    <th>Email</th>
    
    <th>UserType</th>
    <th>Suppression</th>
    <th>Modification</th>
                  </tr>
                </thead>
                <tbody>
                  {% for user in users %}
    <tr>
    <td>{{ user.fullName }}</td>
    <td>{{ user.email }}</td>
    
    <td>{{ user.userType }}</td>
    <td>
        {# Assurez-vous que user.id est défini avant de générer l'URL #}
       
            <a class="btn btn-danger" href="{{ path('supp_user', {'id': user.id}) }}">Supprimer</a>
       
        
    </td>
     
    <td>
        {# Lien vers la route de modification, avec l'identifiant de l'utilisateur #}
        <a class="btn btn-success" href="{{ path('modifuser', {'id': user.id}) }}">Modifier</a>
    </td>
    </tr>
    {% endfor %}
                  
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>







<div class="example-wrapper">

{% endblock %}

templates/user/update.html.twig
{% extends 'base.html.twig' %}
{% block sidebar %}
{% endblock %}
{% block header %}
{% endblock %}

{% block body %}

<div style="display: flex;align-items: center;justify-content: center;margin-top: 150px;">

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Update User Backend ADMIN</h5>

            <!-- General Form Elements -->
            {{ form_start(form) }}
            
                <label for="inputText" class="col-sm-4 col-form-label">FullName</label>
                <div class="col-sm-10">
                    {{ form_widget(form.full_name, {attr: {'class': 'form-control'}}) }}
                </div>
           
            
                <label for="inputText" class="col-sm-4 col-form-label">Email</label>
                <div class="col-sm-10">
                    {{ form_widget(form.email, {attr: {'class': 'form-control'}}) }}
                </div>
            
            
               
           
            
                <label for="inputText" class="col-sm-4 col-form-label">UserType</label>
                <div class="col-sm-10">
                    {{ form_widget(form.user_type, {attr: {'class': 'form-control'}}) }}
                </div>
                <br/>
                <div class="col-sn-10" style="display: flex;align-items: center;justify-content: center">
           {{ form_widget(form.Ajouter, {attr: {'class': 'btn btn-primary'}}) }}
           </div>
            {{ form_end(form) }}

        </div>
    </div>

</div>

{% endblock %}